### ISSUE TITLE
normalized vector dot product

### ISSUE THREAD

**Issue by thematrixduo** [antoine77340/MIL-NCE_HowTo100M#10]
Hi! I noticed that in this paper you directly multiply the embedding vectors without normalizing them, as many of the recent self-supervised learning paper has done. Is there a specific reason for not doing the normalization? Thanks!

**Comment by antoine77340** [comment]
Hi,

We have not seen any improvements when performing cosine similarity with temperature instead of a simple dot product.

**Comment by thematrixduo** [comment]
Thank you!
