### ISSUE TITLE
Pre-processed video download

### ISSUE THREAD

**Issue by thebuax** [antoine77340/MIL-NCE_HowTo100M#14]
Hello, 

can you please explain what you mean by preprocessed videos in "Finally the preprocessed HowTo100M videos (12Tb in total)..."? 

How are they preprocessed?

**Comment by antoine77340** [comment]
Hi,

We first removed the audio, and then we rescaled the videos (without. changing the aspect ratio) so that min(height, width) = 256.

**Comment by thebuax** [comment]
Thanks for answering. Closed the issue.
