### ISSUE TITLE
Evaluation on CrossTask and COIN

### ISSUE THREAD

**Issue by medhini** [antoine77340/MIL-NCE_HowTo100M#15]
Thank you for making your code public! Would you also be releasing the evaluation pipeline for CrossTask and COIN?

**Comment by antoine77340** [comment]
Hi,

Unfortunately, the code I used to evaluate on CrossTask and COIN is using internal code from DeepMind.
So we do not have any plan to release the code, the alternative would be for me (as I did for this repo) to rewrite everything from scratch but I do not have bandwidth for that unfortunately :(

However, if you need any implementation detail, I will be happy to provide them.
