### ISSUE TITLE
hi,about your loss ~~

### ISSUE THREAD

**Issue by jun0wanan** [antoine77340/MIL-NCE_HowTo100M#20]
hi , dear author:

  Thank you open your code~~ I don't know if you can write a simple code to give a example to use MIL-NCE loss ? ╥﹏╥..., I afraid I use it worsely ...

 
Best,
jun (●'◡'●)

**Comment by antoine77340** [comment]
Hi,
You can find the MIl_NCE loss here: https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/master/loss.py#L8
where you only need to provide the text (shape (B*N)xD) and video embeddings (shape (BxD)).

**Comment by jun0wanan** [comment]
> Hi,
> You can find the MIl_NCE loss here: https://github.com/antoine77340/MIL-NCE_HowTo100M/blob/master/loss.py#L8
> where you only need to provide the text (shape (B*N)xD) and video embeddings (shape (BxD)).

Thank you your reply
I have a question ...  I don't know  why denominator - nominator other than  nominator - denominator

![image](https://user-images.githubusercontent.com/54523624/116371790-62906100-a83e-11eb-8b66-397fb8be7cee.png)

**Comment by antoine77340** [comment]
Hi!
This is because the loss is the negative log-likelihood, so we minimize -log instead of log.
That's why it is: nominator - denominator.
