### ISSUE TITLE
Could you release the checkpoint?

### ISSUE THREAD

**Issue by fake-warrior8** [antoine77340/MIL-NCE_HowTo100M#26]
Hi, I can not find the checkpoint link. Could you release the checkpoint?

**Comment by antoine77340** [comment]
Hi,

The checkpoint is in a different github repo here:  https://github.com/antoine77340/S3D_HowTo100M

Antoine

**Comment by fake-warrior8** [comment]
> Hi,
> 
> The checkpoint is in a different github repo here: https://github.com/antoine77340/S3D_HowTo100M
> 
> Antoine

Thank you!
